server:
  context-path: /
  port: 8080

zuul:
  routes:
    library:
      url: http://localhost:8180/library
    bookstore:
      url: http://localhost:8280/bookstore

ribbon:
  eureka:
    enabled: false